// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: products.proto

package products

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Products service

type ProductsService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Products_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Products_PingPongService, error)
}

type productsService struct {
	c    client.Client
	name string
}

func NewProductsService(name string, c client.Client) ProductsService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.service.products"
	}
	return &productsService{
		c:    c,
		name: name,
	}
}

func (c *productsService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Products.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Products_StreamService, error) {
	req := c.c.NewRequest(c.name, "Products.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &productsServiceStream{stream}, nil
}

type Products_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type productsServiceStream struct {
	stream client.Stream
}

func (x *productsServiceStream) Close() error {
	return x.stream.Close()
}

func (x *productsServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productsServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productsServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *productsService) PingPong(ctx context.Context, opts ...client.CallOption) (Products_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Products.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &productsServicePingPong{stream}, nil
}

type Products_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type productsServicePingPong struct {
	stream client.Stream
}

func (x *productsServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *productsServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productsServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productsServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *productsServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Products service

type ProductsHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Products_StreamStream) error
	PingPong(context.Context, Products_PingPongStream) error
}

func RegisterProductsHandler(s server.Server, hdlr ProductsHandler, opts ...server.HandlerOption) error {
	type products interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Products struct {
		products
	}
	h := &productsHandler{hdlr}
	return s.Handle(s.NewHandler(&Products{h}, opts...))
}

type productsHandler struct {
	ProductsHandler
}

func (h *productsHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ProductsHandler.Call(ctx, in, out)
}

func (h *productsHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ProductsHandler.Stream(ctx, m, &productsStreamStream{stream})
}

type Products_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type productsStreamStream struct {
	stream server.Stream
}

func (x *productsStreamStream) Close() error {
	return x.stream.Close()
}

func (x *productsStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productsStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productsStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *productsHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.ProductsHandler.PingPong(ctx, &productsPingPongStream{stream})
}

type Products_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type productsPingPongStream struct {
	stream server.Stream
}

func (x *productsPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *productsPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productsPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productsPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *productsPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
